# Generated by Django 5.0.2 on 2024-07-01 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('readOnly', models.BooleanField(default=False, null=True)),
                ('timeZone', models.CharField(default=None, max_length=255, null=True)),
                ('draggable', models.BooleanField(default=True, null=True)),
                ('resizable', models.BooleanField(default=True, null=True)),
                ('children', models.CharField(default=None, max_length=255, null=True)),
                ('allDay', models.BooleanField(default=False, null=True)),
                ('duration', models.FloatField(default=None, null=True)),
                ('durationUnit', models.CharField(default='day', max_length=255, null=True)),
                ('startDate', models.DateTimeField(default=None, null=True)),
                ('endDate', models.DateTimeField(default=None, null=True)),
                ('exceptionDates', models.JSONField(default=None, null=True)),
                ('recurrenceRule', models.CharField(default=None, max_length=255, null=True)),
                ('cls', models.CharField(default=None, max_length=255, null=True)),
                ('eventColor', models.CharField(default=None, max_length=255, null=True)),
                ('eventStyle', models.CharField(default=None, max_length=255, null=True)),
                ('iconCls', models.CharField(default=None, max_length=255, null=True)),
                ('style', models.CharField(default=None, max_length=255, null=True)),
            ],
            options={
                'db_table': 'events',
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('eventColor', models.CharField(default=None, max_length=255, null=True)),
                ('readOnly', models.BooleanField(default=False, null=True)),
                ('expanded', models.BooleanField(blank=True, default=False, null=True)),
            ],
            options={
                'db_table': 'resources',
            },
        ),
        migrations.CreateModel(
            name='Dependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fromSide', models.CharField(default='right', max_length=255, null=True)),
                ('toSide', models.CharField(default='left', max_length=255, null=True)),
                ('cls', models.CharField(default=None, max_length=255, null=True)),
                ('lag', models.FloatField(default=0, null=True)),
                ('lagUnit', models.CharField(default='day', max_length=255, null=True)),
                ('type', models.IntegerField(blank=True, default=2, null=True)),
                ('fromEvent', models.ForeignKey(db_column='from', on_delete=django.db.models.deletion.CASCADE, related_name='from_dependencies', to='scheduler.event')),
                ('toEvent', models.ForeignKey(db_column='to', on_delete=django.db.models.deletion.CASCADE, related_name='to_dependencies', to='scheduler.event')),
            ],
            options={
                'db_table': 'dependencies',
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventId', models.ForeignKey(db_column='eventId', on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='scheduler.event')),
                ('resourceId', models.ForeignKey(db_column='resourceId', on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='scheduler.resource')),
            ],
            options={
                'db_table': 'assignments',
            },
        ),
    ]
